import { GoalType } from './goal-taxonomy';

export type PlanPattern = 
  | 'TIME_BLOCK_SCHEDULER'
  | 'IF_THEN_TRIGGER_PLAN'
  | 'PROGRESSION_LEVELS'
  | 'MILESTONE_WBS'
  | 'METRIC_TRACKER_WITH_RATE'
  | 'EXPERIMENT_LOOP'
  | 'CADENCE_TOUCHPOINTS'
  | 'SCENARIO_GATES';

export const GOAL_TYPE_PATTERNS: Record<GoalType, PlanPattern[]> = {
  RECURRENT_HABIT: ['TIME_BLOCK_SCHEDULER', 'IF_THEN_TRIGGER_PLAN'],
  SKILL_ACQUISITION: ['PROGRESSION_LEVELS', 'TIME_BLOCK_SCHEDULER'],
  FINITE_PROJECT: ['MILESTONE_WBS'],
  QUANT_TARGET_TRACKING: ['METRIC_TRACKER_WITH_RATE'],
  IDENTITY_EXPLORATION: ['EXPERIMENT_LOOP'],
  RELATIONAL_EMOTIONAL: ['CADENCE_TOUCHPOINTS'],
  HIGH_UNCERTAINTY_TRANSFORM: ['SCENARIO_GATES', 'MILESTONE_WBS'],
};
